VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = yes
BOOTMAGIC_ENABLE = no

COMMAND_ENABLE = no

QMK_SETTINGS = yes

KEY_OVERRIDE_ENABLE = no

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

HAPTIC_ENABLE = yes
HAPTIC_DRIVER = drv2605l

DYNAMIC_MACRO_ENABLE = no
SWAP_HANDS_ENABLE = yes

AUDIO_ENABLE = no
MUSIC_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812  # RGB matrix driver support
RGB_MATRIX_SUPPORTED = yes

VIAL_ENCODERS_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes
