VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = yes
BOOTMAGIC_ENABLE = no

COMMAND_ENABLE = no

QMK_SETTINGS = yes

KEY_OVERRIDE_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
SWAP_HANDS_ENABLE = yes

AUDIO_ENABLE = no
MUSIC_ENABLE = no

VIAL_INSECURE = yes
